export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const TEMP_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const TEMP_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const TEMP_PASSWORD_FAIL    = "FORGOT_PASSWORD_FAIL";


export const ADD_MOBILE_REQUEST = "ADD_MOBILE_REQUEST";
export const ADD_MOBILE_SUCCESS = "ADD_MOBILE_SUCCESS";
export const ADD_MOBILE_FAIL    = "ADD_MOBILE_FAIL";

export const ADD_MOBILE_verify_REQUEST = "LOAD_USER_REQUEST";
export const ADD_MOBILE_verify_SUCCESS = "LOAD_USER_SUCCESS";
export const ADD_MOBILE_verify_FAIL    = "LOAD_USER_FAIL";

export const TXT_PSWD_REQUEST = "LOAD_USER_REQUEST";
export const TXT_PSWD_SUCCESS = "LOAD_USER_SUCCESS";
export const TXT_PSWD_FAIL    = "LOAD_USER_FAIL";

export const EMAIL_PSWD_REQUEST = "LOAD_USER_REQUEST";
export const EMAIL_PSWD_SUCCESS = "LOAD_USER_SUCCESS";
export const EMAIL_PSWD_FAIL    = "LOAD_USER_FAIL";

export const EMAIL_verify_REQUEST = "LOAD_USER_REQUEST";
export const EMAIL_verify_SUCCESS = "LOAD_USER_SUCCESS";
export const EMAIL_verify_FAIL    = "LOAD_USER_FAIL";

export const ADD_ADDRESS_REQUEST = "LOAD_USER_REQUEST";
export const ADD_ADDRESS_SUCCESS = "LOAD_USER_SUCCESS";
export const ADD_ADDRESS_FAIL    = "LOAD_USER_FAIL";

export const CREATE_PSWD_REQUEST = "LOAD_USER_REQUEST";
export const CREATE_PSWD_SUCCESS = "LOAD_USER_SUCCESS";
export const CREATE_PSWD_FAIL    = "LOAD_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_EMAIL = "CLEAR_EMAIL";


export const VERIFY_EMAIL_URL_REQUEST = "VERIFY_EMAIL_URL_REQUEST";
export const VERIFY_EMAIL_URL_SUCCESS = "VERIFY_EMAIL_URL_SUCCESS";
export const VERIFY_EMAIL_URL_FAIL = "VERIFY_EMAIL_URL_FAIL";

export const FORGOT_PASSWORD_INITIAL = "FORGOT_PASSWORD_INITIAL";

export const CHECK_USERNAME_AVIALABLITY = "CHECK_USERNAME_AVIALABLITY";
export const CHECK_USERNAME_AVIALABLITY_SUCCESS = "CHECK_USERNAME_AVIALABLITY_SUCCESS";
export const CHECK_USERNAME_AVIALABLITY_FAIL = "CHECK_USERNAME_AVIALABLITY_FAIL";

export const  UPDATE_EMAIL = "VERIFY_EMAIL_URL_FAIL";
export const UPDATE_EMAIL_SUCCESS = "VERIFY_EMAIL_URL_SUCCESS";
export const UPDATE_EMAIL_FAIL = "VERIFY_EMAIL_URL_FAIL";


